apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces/fluxcd-kustomization.yaml
- system/fluxcd-kustomization.yaml
- backend/fluxcd-kustomization.yaml
- ats/fluxcd-kustomization.yaml
