apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrepository.yaml
- helmrelease.yaml

configMapGenerator:
- name: helm-values-metrics-server
  namespace: flux-system
  files:
  - values.yaml

configurations:
- configuration.yaml
